/**
 * Build data/lexicon/entries.json from the Bugis Wikipedia dump.
 *
 * # What this corpus can and cannot support
 *
 * It cannot support frequency bands. 85% of the dump is bot-generated French
 * commune stubs, and a further 618 articles repeat one image-caption legend
 * verbatim; after removing every bot-generated article, 836 real articles and
 * ~21k tokens remain. A "core" band derived from a template repeated 618 times
 * would be a claim about a bot, not about Bugis. So every entry ships as
 * `band: "unknown"` — see the band description in entries.json.
 *
 * What it can support is ATTESTATION: this form occurs in Bugis Wikipedia
 * article text, in N distinct articles. That is true, checkable, and enough to
 * drive the reader's enumeration, which is the point.
 *
 * It is still a weak claim, and the weakness is real rather than theoretical:
 * the surviving text contains Indonesian (`sekitar`, `adalah`, `selatan`),
 * English (`of`), and Vietnamese place names (`binh`, `quang`) alongside genuine
 * Bugis. Nothing here can tell them apart — doing so needs the dictionary, which
 * is what a lexicon is supposed to be. So every entry carries
 * `attestation: "corpus"`, the reader badges it, and rank.ts scores it low.
 * A reader is told exactly what is behind a reading.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
// @ts-expect-error — .mjs sibling, no types
import { ensureDump } from './corpus-fetch.mjs'
import { interpret } from '../lib/engine/interpret'

/**
 * Articles generated by a bot from a template. Their word counts describe the
 * template, not the language, so they are removed entirely rather than
 * down-weighted.
 */
const BOT_ARTICLE =
  /\{\{\s*(?:France-geo-stub|Komun[ _])|\{\{\s*color box|komun ri déparetema|Komun ri Perancisi/i

/**
 * Wiki and markup remnants that survive cleaning. Only tokens that cannot be a
 * Bugis word are listed — this is not a stoplist for foreign words, because
 * deciding which words are Bugis is exactly what this repo cannot do yet.
 */
const MARKUP = new Set([
  'br', 'px', 'jmpl', 'thumb', 'thumbnail', 'katagori', 'kategori', 'pranala',
  'reflist', 'reflist', 'colspan', 'rowspan', 'align', 'style', 'class',
  'width', 'height', 'url', 'isbn', 'doi', 'pdf', 'html', 'www', 'com', 'org',
  'redirect', 'defaultsort', 'nowiki', 'gallery', 'infobox', 'commonscat',
])

/** Appear in at least this many distinct articles. Drops one-off typos. */
const MIN_DOCUMENT_FREQUENCY = 2

/**
 * Remove `[[Berkas:…]]`, `[[File:…]]`, `[[Kategori:…]]` including nested links.
 * A single regex cannot do this — the captions nest `[[…]]` inside themselves,
 * which is where `jmpl` and `px` leaked from in the first place.
 */
function stripMediaLinks(text: string): string {
  let out = text
  for (;;) {
    const next = out.replace(/\[\[(?:Berkas|File|Kategori|Category|Image)\s*:[^[\]]*\]\]/gi, ' ')
    if (next === out) return next
    out = next
  }
}

function stripTemplates(text: string): string {
  let out = text
  for (;;) {
    const next = out.replace(/\{\{[^{}]*\}\}/g, ' ')
    if (next === out) return next
    out = next
  }
}

function cleanWikitext(text: string): string {
  let out = text
  out = out.replace(/&lt;ref[\s\S]*?&lt;\/ref&gt;/g, ' ')
  out = stripTemplates(out)
  out = out.replace(/\{\|[\s\S]*?\|\}/g, ' ') // tables
  out = stripMediaLinks(out)
  out = out.replace(/\[\[[^\]|]*\|/g, ' ') // piped link target
  out = out.replace(/\[\[|\]\]/g, ' ')
  out = out.replace(/\[https?:\/\/[^\]]*\]/g, ' ')
  out = out.replace(/https?:\/\/\S+/g, ' ')
  out = out.replace(/&lt;[^&]*&gt;/g, ' ') // html tags
  out = out.replace(/&[a-z]+;/g, ' ') // entities
  // Runs of two or more apostrophes are italic/bold markup. A SINGLE apostrophe
  // is left alone: it is the glottal stop, and stripping it would destroy an
  // entire ambiguity class — salo', aru', dare', baiccu'.
  out = out.replace(/'{2,}/g, ' ')
  out = out.replace(/^[*#:;|!].*$/gm, ' ') // list and table rows
  return out
}

const TOKEN = /[a-zé']+/g

async function main() {
  const dump = await ensureDump({ quiet: true })
  const xml = readFileSync(dump.xml, 'utf8')

  const articles = [...xml.matchAll(/<page>([\s\S]*?)<\/page>/g)]
    .map((m) => {
      const body = m[1] ?? ''
      return {
        title: /<title>([\s\S]*?)<\/title>/.exec(body)?.[1] ?? '',
        ns: /<ns>(\d+)<\/ns>/.exec(body)?.[1] ?? '',
        text: /<text[^>]*>([\s\S]*?)<\/text>/.exec(body)?.[1] ?? '',
      }
    })
    .filter((p) => p.ns === '0')

  const real = articles.filter((p) => !BOT_ARTICLE.test(p.text))

  const documents = new Map<string, Set<string>>()
  let tokenCount = 0

  for (const article of real) {
    for (const match of cleanWikitext(article.text).toLowerCase().matchAll(TOKEN)) {
      // Leading apostrophes only — a trailing one is the glottal stop.
      const token = (match[0] ?? '').replace(/^'+/, '')
      if (token.length < 2) continue
      tokenCount += 1
      const seen = documents.get(token) ?? new Set<string>()
      seen.add(article.title)
      documents.set(token, seen)
    }
  }

  const rejected = { markup: 0, rare: 0, unwritable: 0 }
  const entries: unknown[] = []

  for (const [latin, inArticles] of [...documents.entries()].sort(([a], [b]) =>
    a.localeCompare(b),
  )) {
    if (MARKUP.has(latin)) {
      rejected.markup += 1
      continue
    }
    if (inArticles.size < MIN_DOCUMENT_FREQUENCY) {
      rejected.rare += 1
      continue
    }
    // An entry the rule set cannot write could never be reached by the reader's
    // enumeration, so it would sit in the lexicon looking like coverage.
    const trace = interpret(latin)
    if (trace.steps.some((s) => s.type === 'unhandled') || trace.output.text.length === 0) {
      rejected.unwritable += 1
      continue
    }

    const cited = [...inArticles].sort().slice(0, 3)
    entries.push({
      id: `bugwiki-${dump.date}-${latin}`,
      latin,
      band: 'unknown',
      attestation: 'corpus',
      provenance: {
        source: 'Bugis Wikipedia (bug.wikipedia.org), pages-articles dump',
        locator: `${inArticles.size} article(s), e.g. ${cited.join('; ')}`,
        licence: 'CC BY-SA 4.0',
        licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
        retrieved: `${dump.date.slice(0, 4)}-${dump.date.slice(4, 6)}-${dump.date.slice(6, 8)}`,
      },
    })
  }

  const output = {
    $comment:
      'Generated by `pnpm lexicon:extract`. Do not hand-edit — regenerate instead.\n\n' +
      'ATTESTATION, NOT FREQUENCY, AND NOT A DICTIONARY. Every entry means "this form occurs in ' +
      'Bugis Wikipedia article text, in at least two distinct non-bot-generated articles". It does ' +
      'NOT mean the form is a Bugis word: the corpus contains Indonesian, English and Vietnamese ' +
      'place names, and nothing here can tell them apart. Entries are marked attestation:"corpus", ' +
      'the reader badges them, and rank.ts scores them low. See data/lexicon/provenance.md.',
    version: '0.1.0',
    source: {
      corpus: 'Bugis Wikipedia (bug.wikipedia.org)',
      dumpDate: dump.date,
      dumpUrl: dump.url,
      dumpSha256: dump.sha256,
      licence: 'CC BY-SA 4.0',
      attribution: 'Bugis Wikipedia contributors',
      articlesInDump: articles.length,
      articlesAfterRemovingBotGenerated: real.length,
      tokensCounted: tokenCount,
      minDocumentFrequency: MIN_DOCUMENT_FREQUENCY,
      botArticleFilter: String(BOT_ARTICLE),
    },
    bands: {
      unknown: {
        weight: 1,
        description:
          'No frequency evidence. EVERY entry is here on purpose: 85% of the dump is ' +
          'bot-generated French commune stubs and a further 618 articles repeat one caption ' +
          'verbatim, so a frequency band derived from this corpus would describe a template ' +
          'rather than the language. A band is a claim about frequency and this corpus cannot ' +
          'support one.',
      },
    },
    entries,
  }

  writeFileSync(
    join(process.cwd(), 'data/lexicon/entries.json'),
    `${JSON.stringify(output, null, 2)}\n`,
  )

  console.log(`lexicon:extract — bug.wikipedia dump ${dump.date}`)
  console.log(`  ${articles.length} artikel ns0 → ${real.length} setelah membuang hasil bot`)
  console.log(`  ${tokenCount} token, ${documents.size} bentuk berbeda`)
  console.log(`  ditolak: ${rejected.rare} terlalu jarang (df<${MIN_DOCUMENT_FREQUENCY}), ` +
    `${rejected.markup} sisa markup, ${rejected.unwritable} tak dapat dituliskan aturan`)
  console.log(`  ${entries.length} lema ditulis ke data/lexicon/entries.json`)
  console.log('')
  console.log('  Semua band "unknown" dengan sengaja. Korpus ini menopang KETERBUKTIAN, bukan frekuensi.')
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error)
  process.exit(1)
})
