/**
 * Generate the lexicon the browser gets.
 *
 * `data/lexicon/entries.json` is the auditable source and stays exactly as it
 * is: one provenance record per entry, because invariant 13 says every entry
 * carries its provenance and a reviewer has to be able to check any one of them
 * against the file.
 *
 * The browser needs the same facts, not the same shape. Measured on the shipped
 * file, 70% of it is provenance, and three of provenance's four fields hold ONE
 * distinct value across all 1,323 entries — source, licence and retrieved were
 * being transmitted 1,323 times each. Only `locator` varies, and only 994 ways.
 *
 * So this writes the same information with the constants hoisted out and the
 * locators pooled. Nothing is dropped: the reading tree renders source, locator
 * and licence, and all three survive.
 *
 * Wired into `pnpm build` ahead of `next build`, and checked by
 * tests/lexicon-compact.test.ts, which regenerates from entries.json and fails
 * if the committed file differs. A derived artifact nobody re-derives is a
 * stale artifact; this one cannot go stale without the suite going red.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { LexiconSchema } from '../lib/lexicon/loader'

const ROOT = process.cwd()
const SOURCE = join(ROOT, 'data/lexicon/entries.json')
const TARGET = join(ROOT, 'data/lexicon/compact.json')

export type CompactLexicon = {
  $comment: string
  version: string
  bands: Record<string, { weight: number; description: string }>
  /** The fields that were identical on every entry. */
  provenance: { source: string; licence: string; licenceUrl?: string; retrieved: string }
  /** Every distinct locator, referenced by index. */
  locators: string[]
  /** `[id, latin, band, attestation, locatorIndex]` per entry. */
  entries: [string, string, string, string, number][]
}

export function compact(raw: unknown): CompactLexicon {
  const parsed = LexiconSchema.parse(raw)
  const first = parsed.entries[0]?.provenance

  if (!first) throw new Error('lexicon-compact: entries.json is empty')

  for (const entry of parsed.entries) {
    const p = entry.provenance
    if (p.source !== first.source || p.licence !== first.licence || p.retrieved !== first.retrieved) {
      throw new Error(
        `lexicon-compact: ${entry.id} has a provenance source/licence/retrieved that differs ` +
          `from the rest. The compact form hoists those out as constants, so it can no longer ` +
          `represent this lexicon — extend the format rather than dropping the difference.`,
      )
    }
  }

  const locators = [...new Set(parsed.entries.map((e) => e.provenance.locator))].sort((a, b) =>
    a.localeCompare(b),
  )
  const index = new Map(locators.map((l, i) => [l, i]))

  return {
    $comment:
      'GENERATED by `pnpm lexicon:compact` from entries.json — do not edit. This is the shape ' +
      'the browser loads; entries.json remains the auditable source, one provenance per entry.',
    version: parsed.version,
    bands: parsed.bands as CompactLexicon['bands'],
    provenance: {
      source: first.source,
      licence: first.licence,
      ...(first.licenceUrl ? { licenceUrl: first.licenceUrl } : {}),
      retrieved: first.retrieved,
    },
    locators,
    entries: parsed.entries.map((e) => [
      e.id,
      e.latin,
      e.band,
      e.attestation,
      index.get(e.provenance.locator)!,
    ]),
  }
}

export function serialise(value: CompactLexicon): string {
  return `${JSON.stringify(value)}\n`
}

/** Only writes when run directly, so importing it from a test is side-effect free. */
if (process.argv[1]?.endsWith('lexicon-compact.ts')) {
  const source = JSON.parse(readFileSync(SOURCE, 'utf8'))
  const out = serialise(compact(source))
  writeFileSync(TARGET, out)
  const before = readFileSync(SOURCE, 'utf8').length
  console.log(
    `lexicon:compact — ${before.toLocaleString()} B entries.json → ` +
      `${out.length.toLocaleString()} B compact.json`,
  )
}
